### ISSUE TITLE
Jest 28 failure: should return an object or a Promise resolving to an object

### ISSUE THREAD

**Issue by granttchart** [remind101/jest-transform-graphql#13]
The following error is being thrown on Jest 28.1.0 due to Jest breaking changes. https://jestjs.io/docs/upgrading-to-jest28#transformer explains the necessary fix.

```    ● Invalid return value:
      `process()` or/and `processAsync()` method of code transformer found at 
      "node_modules/jest-transform-graphql/index.js" 
      should return an object or a Promise resolving to an object. The object 
      must have `code` property with a string of processed code.
      This error may be caused by a breaking change in Jest 28:
      https://jestjs.io/docs/upgrading-to-jest28#transformer
      Code Transformation Documentation:
      https://jestjs.io/docs/code-transformation
```

**Comment by ezmiller** [comment]
+1 also running into this error

**Comment by dep** [comment]
+1 also running into this error.

**Comment by dep** [comment]
@granttchart Have you found a workaround for this?

**Comment by dep** [comment]
Folks ending up here might have some luck switching to this:

https://www.npmjs.com/package/@graphql-tools/jest-transform

**Comment by dobesv** [comment]
[@graphql-tools/jest-transform](https://www.npmjs.com/package/@graphql-tools/jest-transform) isn't quite compatible, and doesn't allow multiple operations per file.

**Comment by SimonSomlai** [comment]
Worked for me!;

```
npm i -D @graphql-tools/jest-transform

**jest.config.js**
{
  "jest": {
    "transform": {
      "\\.(gql|graphql)$": "@graphql-tools/jest-transform"
    }
  }
}
```

**Comment by andre-muller** [comment]
I was trying to use `@graphql-tools/jest-transform` but it's throwing an error when file has multiple operations.

``` 
  ● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'source')

      36 |  * Used to generate useUseUserProjectsProjectListQuery
      37 |  */
    > 38 | export const USER_PROJECTS_CONNECTION_QUERY = gql`
         |                                                  ^
      39 |   query useUserProjects_ProjectList(
      40 |     $projectFilters: ProjectFilters
      41 |     $listInputs: ListInput

      at ../node_modules/graphql-tag/src/index.ts:127:25
          at Array.forEach (<anonymous>)
      at gql (../node_modules/graphql-tag/src/index.ts:125:8)
      at Object.<anonymous> (src/views/hooks/useUserProjects.tsx:38:50)
      at Object.<anonymous> (src/views/components/UpdateAssigneesDialog/ProjectList.tsx:19:63)
      at Object.<anonymous> (src/views/components/UpdateAssigneesDialog/ProjectReassign.tsx:27:59)
      at Object.<anonymous> (src/views/components/UpdateAssigneesDialog/UpdateAssigneesDialog.tsx:18:63)
      at Object.<anonymous> (src/views/components/UpdateAssigneesDialog/index.ts:9:69)
      at Object.<anonymous> (src/views/components/EditUserDrawer/components/EditUserForm/EditUserForm.tsx:41:69)
      at Object.<anonymous> (src/views/components/EditUserDrawer/components/EditUserForm/EditUserForm.test.tsx:13:60)
      ```

**Comment by monigala** [comment]
> The following error is being thrown on Jest 28.1.0 due to Jest breaking changes. https://jestjs.io/docs/upgrading-to-jest28#transformer explains the necessary fix.
> 
> ```
>       `process()` or/and `processAsync()` method of code transformer found at 
>       "node_modules/jest-transform-graphql/index.js" 
>       should return an object or a Promise resolving to an object. The object 
>       must have `code` property with a string of processed code.
>       This error may be caused by a breaking change in Jest 28:
>       https://jestjs.io/docs/upgrading-to-jest28#transformer
>       Code Transformation Documentation:
>       https://jestjs.io/docs/code-transformation
> ```

The above link to the resolution/explanation results in 404.

**Comment by MasterOdin** [comment]
The first link should be https://jestjs.io/docs/28.x/upgrading-to-jest28#transformer.

**Comment by SethDavenport** [comment]
Should be able to do something like this then:

jest.config.js:
```json
{
  "jest": {
    "transform": {
      "\\.(gql|graphql)$": "./transform-graphql-jest-28-shim.js"
    }
  }
}
```

transform-graphql-jest-28-shim.js:
```js
const { process: upstreamProcess } = require('jest-transform-graphql');

const process = (...args) => {
  const code = upstreamProcess(...args);
  return { code };
};

module.exports = { process };
```

**Comment by dep** [comment]
Thank you @SethDavenport this is a great solution.

**Comment by yogeshgadge** [comment]
Neither of these workarounds worked jest 29.6.4 in a Typescript project

It works fine in rollup build but I am unit testing my source.

**Comment by anewstead** [comment]
@yogeshgadge 
> Neither of these workarounds worked jest 29.6.4 in a Typescript project
> 
> It works fine in rollup build but I am unit testing my source.

thought i had this too, try running 
`jest --clearCache`
and retry with @SethDavenport shim
worked for me

**Comment by jorgequintt** [comment]
> Should be able to do something like this then:
> 
> jest.config.js:
> 
> ```json
> {
>   "jest": {
>     "transform": {
>       "\\.(gql|graphql)$": "./transform-graphql-jest-28-shim.js"
>     }
>   }
> }
> ```
> 
> transform-graphql-jest-28-shim.js:
> 
> ```js
> const { process: upstreamProcess } = require('jest-transform-graphql');
> 
> const process = (...args) => {
>   const code = upstreamProcess(...args);
>   return { code };
> };
> 
> module.exports = { process };
> ```

This was a life saver. Thank you very much

**Comment by whizzzkid** [comment]
Here's the ESM compatible shim `jest-28-gql-transform-shim.mjs`

```js
import { process as upstreamProcess } from 'jest-transform-graphql';

const process = (...args) => {
  const code = upstreamProcess(...args);
  return { code };
};

const transformer = { process };
export default transformer;
```
