### ISSUE TITLE
Support definitions

### ISSUE THREAD

**Issue by mrasoahaingo** [remind101/jest-transform-graphql#2]
I don't know if someone faced the same issue as mine:

```
 ● Test suite failed to run

    TypeError: Cannot read property 'filter' of undefined

      at Object.parser (node_modules/react-apollo/lib/parser.js:12:41)
      at graphql (node_modules/react-apollo/lib/graphql.js:74:30)
```

Definitions is missing on the exported module. 
So I wrote my own transform rules based on the graphql-tag/loader

```
const gql = require('graphql-tag');

// Takes `source` (the source GraphQL query string)
// and `doc` (the parsed GraphQL document) and tacks on
// the imported definitions.
function expandImports(source, doc) {
  const lines = source.split('\n');
  let outputCode = "";

  lines.some((line) => {
    if (line[0] === '#' && line.slice(1).split(' ')[0] === 'import') {
      const importFile = line.slice(1).split(' ')[1];
      const parseDocument = `require(${importFile})`;
      const appendDef = `doc.definitions = doc.definitions.concat(${parseDocument}.definitions);`;
      outputCode += appendDef + "\n";
    }
    return (line.length !== 0 && line[0] !== '#');
  });

  return outputCode;
}

module.exports = {
  process(src, _filename, _config, _options) {
    const doc = gql`${src}`;
    const outputCode = `var doc = ${JSON.stringify(doc)};`;
    const importOutputCode = expandImports(src, doc);

    return outputCode + "\n" + importOutputCode + "\n" + `module.exports = doc;`;
  },
};

```

And the jest config:

```
      "^.+\\.(gql|graphql)$": "<rootDir>/config/jest/graphqlTransform.js"
```

This work fine now

**Comment by xavcz** [comment]
This got fixed with v2.1.0 normally 👍  I believe we can close this issue 🙃
